# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\KEVIN\Programming\Projects\Sudoku\View\ui\SolvedView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from Repository.ScoreManager import ScoreManager, Score

class SolvedView(QDialog):
    def __init__(self, widget, gameView, score_manager: ScoreManager, topScoreUpdateFunc):
        super(SolvedView, self).__init__()
        self.setupUi(self)
        self.widget = widget
        self.score_manager = score_manager
        self.topScoreUpdate_func = topScoreUpdateFunc

        self.score: int = None
        self.difficulty = gameView.game.difficulty_level

        self.gameView = gameView
        self.timeLabel.setText(gameView.stopwatch.time_taken_in_text)
        self.submitButton.clicked.connect(self.finishGame)

    def finishGame(self):
        completor_name = self.nameTextEdit.toPlainText()
        if not completor_name == "":
            self.score_manager.input_score(Score(completor_name, self.gameView.stopwatch.getTimeInSec(), self.gameView.game.difficulty_level, self.score))
            widget_to_remove = self.widget.widget(4)
            widget_to_remove.deleteLater()
            self.widget.removeWidget(widget_to_remove)
            self.topScoreUpdate_func()
            self.close()
            self.gameView.backToMainMenu()
        else:
            self.textEditLabel.setText("Type your name here (input required): ")
            self.textEditLabel.setStyleSheet('color: red')


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 615)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 351, 181))
        font = QtGui.QFont()
        font.setFamily("A bit sketchy")
        font.setPointSize(54)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.submitButton = QtWidgets.QPushButton(Dialog)
        self.submitButton.setGeometry(QtCore.QRect(80, 440, 231, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.nameTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.nameTextEdit.setGeometry(QtCore.QRect(80, 390, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.nameTextEdit.setFont(font)
        self.nameTextEdit.setPlainText("")
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 300, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.timeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout.addWidget(self.timeLabel)
        self.textEditLabel = QtWidgets.QLabel(Dialog)
        self.textEditLabel.setGeometry(QtCore.QRect(80, 370, 231, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEditLabel.setFont(font)
        self.textEditLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.textEditLabel.setObjectName("textEditLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sudoku"))
        self.label_6.setText(_translate("Dialog", "Game\n"
"Solved!"))
        self.submitButton.setText(_translate("Dialog", "Submit Result"))
        self.label.setText(_translate("Dialog", "Time Spent:"))
        self.timeLabel.setText(_translate("Dialog", "00 : 00"))
        self.textEditLabel.setText(_translate("Dialog", "Type your name here: "))
